trigger:
  branches:
    include:
      #- main
      - dev
  
pool: 
  name: default
  demands: agent.name -equals ayushagent  #strictly to run on specific agent

stages:
  - stage: tf_plan
    displayName: "Terraform plan"
    jobs:   # each stage can have multiple jobs can be run in parallel or sequentially with condition
      - job: terraform_init
        steps:
          - checkout: self
          - script: |
              terraform init
         
          # publish .terraform and .terraform.lock.hcl as pipeline artifacts
          - task: PublishBuildArtifacts@1  
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)/.terraform'
              ArtifactName: 'terraform_init_artifact'
              publishLocation: 'Container'

          - task: PublishBuildArtifacts@1  
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)/.terraform.lock.hcl'
              ArtifactName: 'tf_lock'
              publishLocation: 'Container'

      - job: terraform_fmt
        steps: 
          - checkout: self
          - script: |
              terraform fmt -check

      - job: terraform_validate
        dependsOn: terraform_init
        steps:
          - checkout: self
          #download previously published artifacts 
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              ArtifactName: 'terraform_init_artifact'
              downloadPath: '$(Build.SourcesDirectory)'
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              ArtifactName: 'tf_lock'
              downloadPath: '$(Build.SourcesDirectory)'
              
          - script: |
              terraform validate
              


