trigger:
  branches:
    include:
      #- main
      - dev
  
pool: 
  name: default
  demands: agent.name -equals ayushagent  #strictly to run on specific agent

variables:
  terraformDir: 'terraform'

stages:
  - stage: tf plan
    displayName: "Terraform plan"
    jobs:   # each stage can have multiple jobs can be run in parallel or 
      - job: terraform_init
        steps:
          - checkout: self
          - script: |
              terraform init

      - job: terraform_fmt
        steps: 
          - checkout: self
          - script: |
              terraform fmt -check

      - job: terraform_validate
        dependsOn: terraform_init
        steps:
          - checkout: self
          - script: |
              terraform validate
              


