trigger:
  branches:
    include:
      #- main
      - dev
  
pool: 
  name: default
  demands: agent.name -equals ayushagent  #strictly to run on specific agent

variables:
  terraformDir: 'terraform'

stages:
  - stage: init
    displayName: "Terraform Init"
    jobs:              # each stage can have multiple jobs can be run in parallel or 
      - job: terraform_init
        steps:
          - checkout: self
          - script: |
              terraform init
              terraform fmt -check
              terraform validate




